services:
  vault:
    image: hashicorp/vault:latest
    ports:
      - "8200:8200"
    volumes:
      - /opt/vault/config/vault.json:/vault/config/vault.json
      - /opt/vault/policies/:/vault/policies/
      - vault:/vault/data
      
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/vault.json
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
    networks:
      - core
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s 
        window: 60s
      placement:
        constraints:
          - node.role == manager

networks:
  core:
    external: true

volumes:
  vault:
    driver: local
